### ISSUE TITLE
Analyze edge cases

### ISSUE THREAD

**Issue by joshuago78** [gri-is/lodjob#18]

**Comment by mdlincoln** [comment]
I think this issue is too broad and can be closed. I can review how well distinct new features are handling edge cases, but that's probably best addressed on an issue-by-issue basis.

**Comment by mdlincoln** [comment]
(Might also close #13 while we're at it?)

**Comment by melissaagill** [comment]
@mdlincoln i agree here. @joshuago78 is it okay to close?
