### ISSUE TITLE
script for artist

### ISSUE THREAD

**Issue by joshuago78** [gri-is/lodjob#34]
- use autosuggest tool
- someone (not Nathan) will perform QA on 5%? of exact matches
- reimport matches to Star with ULAN IDs

**Comment by nlomeli** [comment]
Gregg Garcia and Vladamir have also recommended considering Wikidata as a source of tests sets for ULAN, TGN, and even AAT services.  A large number of Wikidata records purport to have been manually reconciled to these vocabularies:
 
https://tools.wmflabs.org/mix-n-match/
(see ULAN / TGN > Manually matched)

**Comment by joshuago78** [comment]
We also need to determine the threshold of difference between the top result and lower results at which we decide that it is an "exact" (single) match.

**Comment by melissaagill** [comment]
On hold until after [updates to auto-suggest service](https://github.com/gri-is/vocabs-autosuggest/issues/6) are completed.

**Comment by melissaagill** [comment]
Closing this issue since this work has moved to the [pir-reconciliation](https://github.com/gri-is/pir-reconciliation) repository.
