### ISSUE TITLE
empty dimensions in source should not return error

### ISSUE THREAD

**Issue by mdlincoln** [gri-is/lodjob#36]
In many records, `source.dimensions` is blank. This should return a `skip` status rather than `error`

**Comment by nlomeli** [comment]
This is now fixed.  Such a case is being logged like so:

{'args': {'dimensions': 'dimensions'},
   'datetime': '2017-05-12 01:38:38.287686',
   'message': 'missing dimensions value',
   'pathname': 'jobs.knoedler.tasks.dimensions',
   'status': 'skip'}

and flagged like so:

'dimensions': 'skip'

The **derived** data appears as follows, which can be changed:

'dimensions': None
