### ISSUE TITLE
add tests

### ISSUE THREAD

**Issue by joshuago78** [gri-is/lodjob#45]

**Comment by melissaagill** [comment]
Should be prioritized after (auto-suggest updates)[https://github.com/gri-is/vocabs-autosuggest/issues/6] are resolved because of dependencies, noted above.

**Comment by mdlincoln** [comment]
Once @nlomeli sets up the basic architecture for tests, I should probably be able to grok the style and compose many of them myself.

**Comment by mdlincoln** [comment]
Closed by 8c4f5e0a3b4f67bdeedb20c82e3ed34f2c6fe362
