### ISSUE TITLE
Convert dimensions to numeric values

### ISSUE THREAD

**Issue by mdlincoln** [gri-is/lodjob#46]
To do this, I think the current [`split_dimensions()`](https://github.com/gri-is/lodjob/blob/master/utils/dimension_parsing.py#L20-L27) function needs to be broken out in to four different steps/functions

1. Split up multiple dimensions (This is already implemented)
1. Separate out multiple components of those dimensions, e.g. decompose `12' 5 1/2"` in to `12'` and `5 1/2"` (n.b. there aren't a lot of feet+inches in Knoedler, but there are many thousands of them in sales)
	- Starting from a subcomponent, I've used `^([0-9/\\. ]*)(\\D*)([0-9/\\. ]*)(\\D*)` to split this in to subcomponent numbers and their respective (possible) units
2. Parse each of those measurement subcomponents into numeric values with units, in particular parsing fractions: `"5 1/2"` in to `5.5`
3. Depending on the units associated with each subcomponent, recompose them in to a single value.
	- For feet/inches, we want to recompose these values as inches. So `12' 5 1/2"` should be `12 * 12 + 5.5 = 149.5`.
	- Unfortunately there are a lot of variations on this - often you'll see only `12' 5 1/2` without any `"` mark, and also vice versa. I suggest let's get the two cases working now
		1. With both feet AND inches marked
		2. When no unit indications are present and there's just one subcomponent (this is the vast majority of Knoedler dimensions) assume inches.

**Comment by mdlincoln** [comment]
Wait for #45

**Comment by mdlincoln** [comment]
I will

- [ ] Add a series of dimension test cases
- [ ] Revise instructions here for parsing dimensions

**Comment by melissaagill** [comment]
Closing this issue since this work has moved to the [pirMerger](https://github.com/gri-is/pirMerger) repository.
