### ISSUE TITLE
Pull data from AAT manual reconciliation tables for Knoedler

### ISSUE THREAD

**Issue by mdlincoln** [gri-is/lodjob#47]
Kelly has manually reconciled terms from the Knoedler `object_type` and `materials` field to AAT concepts. These are recorded in a Google Sheet (@melissaagill has already emailed these to @nlomeli and @joshuago78)

- [ ] Determine a workflow for importing data from these sheets (will need to support iterative harvesting of these tables)
- Based on the combined values of `object_type` and `materials` field in Knoedler, set the values for:
    - [ ] `classified_as` data for objects (http://linked.art/model/object/identity/#types)
        - n.b. for the ease of data entry, these concept IDs have been put in to two columns. These can be treated equally when mapping
    - [ ] the column `made of (materials)` should be mapped to `made_of`: http://linked.art/model/object/physical/#materials
    - [ ] the column `made of (support)` should be mapped to the `made_of` of a `part` of an object: http://linked.art/model/object/physical/#parts
    - [ ] Any values of the `materials` field with no supplied AAT id should be mapped to `MaterialsStatement`: http://linked.art/model/object/physical/#materials-statement
    - [ ] Some combinations of `object_type` and `materials` will also have been assigned a `technique` that should be attached to the object `Production`: http://linked.art/model/provenance/#techniques

**Comment by mdlincoln** [comment]
Waiting for #45

**Comment by melissaagill** [comment]
Closing this issue since this work has moved to the [pirMerger](https://github.com/gri-is/pirMerger) repository.
