### ISSUE TITLE
dimension scripts

### ISSUE THREAD

**Issue by melissaagill** [gri-is/lodjob#8]
convert dimensions to 3 separate fields of height, width, depth.

watch out for circumference

**Comment by azaroth42** [comment]
See: http://linked.art/model/object/physical/#dimensions

Output:
```
"dimension": {
  "id": "uri-goes-here", 
  "type": "Dimension", 
  "classified_as": "aat:300055647",
  "value": 13.75, 
  "unit": {
    "id": "http://vocab.getty.edu/aat/300379100", 
    "type": "MeasurementUnit", 
    "label": "inches"
  }
} 
```

**Comment by mdlincoln** [comment]
It is possible for there to be quite a few dimensions (e.g. pi_record_no K-34295 has this for dimensions: `Left panel 9 1/2 x 26, Center panel 20 3/4 x 26 x Right panel 9 1/2 x 26`)

The most generalized way I've found to parse these is to capture all matches for the following regex:

````
(?<prefix>[^\d]*)(?<number>[0-9\.]+(?: \d+\/\d+)?)(?<suffix>[^\d]*)
````

This should split out numeric components (allowing for both decimals as well as fractions) while saving the surrounding text. (there are almost surely some edge cases that will break this pattern)

- [ ] extract numeric components using regex
    - [ ] If no numeric matches are found, but there is some content in the field, throw an error (n.b. once we get to sales catalogs there will be a bunch of dimensions that are written out numbers - am working on getting these addressed in STAR)
- [ ] parse fractions and convert to numeric
- [ ] infer unit and dimension from prefix/suffix (:hand-wave.gif)

**Comment by azaroth42** [comment]
FWIW, the parser I wrote:

```
def process_dimensions(dims):
	dims = dims.lower()
	# assume default of inches
	dims = dims.replace('"', '')
	dims = dims.replace('in.', '')
	dims = dims.replace('inches', '')
	dims = dims.replace('//', '/')
	dims = dims.replace('[', '')
	dims = dims.replace(']', '')
	dims = dims.replace('X', 'x')
	dl = dims.split('x')

	dimensions = []
	p = 0
	for d in dl:
		d = d.strip()
		# check for (nn n/n)
		which = ""
		m = divre.match(d)
		if m:
			(main, numr, denom, end) = m.groups()
			ttl = int(main) + (float(numr) / float(denom))
		else:
			try:
				ttl = int(d)
			except:
				m = unitre.match(d)
				if m:
					(ttl, which, end) = m.groups()
					if which.startswith('h'):
						which = 'h'
					else:
						which = 'w'
				else:
					# print "----- %s" % d
					continue
		if not which:
			which = "w" if p else "h"
		p += 1
		dimensions.append([ttl, which])
	return dimensions
```
