### ISSUE TITLE
price scripts

### ISSUE THREAD

**Issue by melissaagill** [gri-is/lodjob#9]

**Comment by azaroth42** [comment]
See: http://linked.art/model/provenance/#purchase

```
    "paid_amount": {
      "id": "https://linked.art/example/money/0", 
      "type": "MonetaryAmount", 
      "value": 100, 
      "currency": {
        "id": "https://linked.art/example/money/1", 
        "type": "Currency", 
        "label": "dollars"
      }
    }
```

**Comment by mdlincoln** [comment]
@azaroth42 For unparseable prices, weren't we going to have `MonetaryAmountStatement`s  la http://linked.art/model/object/physical/#dimension-statement ?

**Comment by azaroth42** [comment]
For unparseable prices, we need something that can sit in the right position of the model. So for those, as we don't need to provide a source for them (right?!?) we can just put the data in the label:

```
"paid_amount": {
  "id": "https://.../1",
  "type": "MonetaryAmount",
  "label": "1'2\"9s"
}
```

**Comment by mdlincoln** [comment]
😬 There's a dedicated column for `price_source` that has the catalog copy location code, or other textual source, for prices of ~134,000 records, and a more detailed `price_citation` for ~38,000 german sales that has specific volume / page numbers from those sources. (I for one am _not_ champing at the bit to have those citations modeled down to the page number! But there's probably some desire to have the text stored somewhere.)

FWIW I don't _believe_ we have any cases where we can (much less _need to_) assert multiple prices with each mapped to a distinct source.

**Comment by mdlincoln** [comment]
(working up specs for parsing out prices - will post this week)

**Comment by mdlincoln** [comment]
[Currency sub-unit working document](https://docs.google.com/spreadsheets/d/1q1YwCpueXDA_YL_QSSCdawwwxEsbeCCv9BhTnfbMR8Q/edit?usp=sharing)

**Comment by mdlincoln** [comment]
From discussion with @nlomeli on 2017-04-06

For each monetary amount field (`purch_amount`, `knoedshare_amt`, `price_amount`)

- [ ] Run several string processing functions to strip or extract certain non-numeric character patterns that do not automatically disqualify fields for parsing
    - [ ] [Run amonsieurx transform](https://github.com/gri-is/lodjob/issues/9#issuecomment-292026403)
    - [ ] Remove `[]`s from prices when they match `/^\[\d+\.?\d*\]$/` (i.e. only when they occur at the start and end of the string and enclose numbers only. Brackets appearing in other configurations usually indicate partially illegible prices, which are unparseable). Create boolean flag `has_brackets` based on this match, as this may inform if/where we assign parsed values in the final transformation.
- [ ] Any remaining fields matching `/[a-zA-Z]/` and/or `/\?/` should not be parsed.
- [ ] Run final parsing fn that breaks out numeric components of the string and produces a decimalized number based on the appropriate currency sub-units ([a closure-based implementation of this is described here](http://matthewlincoln.net/2017/03/20/r-closures-and-currency-decimalization.html))
    - currencies for the respective amounts are in `purch_currency`, `knoedshare_curr`, `price_currency`
    - note that separator character may include `/[\.=- ]`
    - [ ] Should error if producing more components than expected for currency (e.g. three components for USD, when we only expect a maximum of two)
    - [ ] Should error if subunit is higher than expected for currency (e.g. if the first sub-unit of an amount in pounds is >= 20)

Nathan let me know on here if you see inconsistencies in these specs or if you figure out a smoother order of operations.
